java -jar ../dist\/milan.jar -o out/add.ms add.mil
java -jar ../dist/jmilan.jar -o out/factorial.ms factorial.mil
java -jar ../dist/jmilan.jar -o out/fib.ms fib.mil
java -jar ../dist/jmilan.jar -o out/gcd.ms gcd.mil
java -jar ../dist/jmilan.jar -o out/if.ms if.mil
java -jar ../dist/jmilan.jar -o out/invert.ms invert.mil
java -jar ../dist/jmilan.jar -o out/loop.ms loop.mil
java -jar ../dist/jmilan.jar -o out/power.ms power.mil
java -jar ../dist/jmilan.jar -o out/read2.ms read2.mil
java -jar ../dist/jmilan.jar -o out/sum.ms sum.mil
java -jar ../dist/jmilan.jar -o out/invalid.ms invalid.mil